"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import type {Market,MarketActivity,Thesis,Post} from "@rush/types";
import {api} from "../../../lib/api";
import {ThesisComposer} from "../../../components/thesis-composer";
import {PostComposer} from "../../../components/post-composer";
import {CommentThread} from "../../../components/comment-thread";
import {ReactionButton} from "../../../components/reaction-button";
import {MarketContext} from "../../../components/market-context";
export default function MarketPage({params}:{params:Promise<{marketId:string}>}){
 const [id,setId]=useState("");const [market,setMarket]=useState<Market|null>(null);const [activity,setActivity]=useState<MarketActivity[]>([]);const [theses,setTheses]=useState<Thesis[]>([]);const [posts,setPosts]=useState<Post[]>([]);const [error,setError]=useState("");
 const load=async(decoded:string)=>{setError("");try{const [m,a,t,p]=await Promise.all([api.market(decoded),api.activity(decoded),api.theses(decoded),api.posts(decoded)]);setMarket(m);setActivity(a.items);setTheses(t.items);setPosts(p.items);}catch(e){setError(e instanceof Error?e.message:"Market unavailable.");}};
 useEffect(()=>{params.then(p=>{const decoded=decodeURIComponent(p.marketId);setId(decoded);load(decoded);});},[params]);
 if(error)return <main className="page"><div className="empty">{error}</div></main>;
 if(!market)return <main className="page"><div className="empty">Loading market…</div></main>;
 return <main className="page"><section className="market-head"><div><div className="muted">{market.chain.toUpperCase()} · {market.provider}</div><h1>{market.symbol}</h1><p className="muted">{market.name}{market.quoteSymbol?" · quoted in "+market.quoteSymbol:""}</p></div><div>{market.priceUsd!=null&&<div className="price">{"$"+market.priceUsd.toLocaleString(undefined,{maximumFractionDigits:8})}</div>}<div className={market.priceChange24h!=null&&market.priceChange24h<0?"red":"green"}>{market.priceChange24h!=null?market.priceChange24h.toFixed(2)+"% 24h":"No 24h change available"}</div></div></section>
 <div className="grid"><div className="card"><div className="muted">Market cap</div><div className="price">{market.marketCapUsd!=null?"$"+market.marketCapUsd.toLocaleString():"—"}</div></div><div className="card"><div className="muted">24h volume</div><div className="price">{market.volume24hUsd!=null?"$"+market.volume24hUsd.toLocaleString():"—"}</div></div><div className="card"><div className="muted">Liquidity</div><div className="price">{market.liquidityUsd!=null?"$"+market.liquidityUsd.toLocaleString():"—"}</div></div></div>
 <MarketContext marketId={id}/><section><div className="section-head"><div><h2>Community</h2><p className="muted">Theses and conversation around this market.</p></div></div><ThesisComposer marketId={id} onCreated={()=>load(id)}/><PostComposer marketId={id} onCreated={()=>load(id)}/><div className="feed">{theses.length===0&&posts.length===0?<div className="empty">No community discussion yet. Be the first to form a view.</div>:<>{theses.map(t=><article key={t.id}><div className="muted">{t.author.displayName} · {t.stance}</div><Link href={"/theses/"+t.id}><h3>{t.title}</h3></Link><p>{t.body}</p><ReactionButton targetType="thesis" targetId={t.id} initialCount={t.reactions}/><CommentThread targetType="thesis" targetId={t.id}/></article>)}{posts.map(p=><article key={p.id}><div className="muted">{p.author.displayName}</div><p>{p.body}</p><ReactionButton targetType="post" targetId={p.id} initialCount={p.reactions}/><CommentThread targetType="post" targetId={p.id}/></article>)}</>}</div></section>
 <section className="card"><h2>Market activity</h2>{activity.length===0?<p className="muted">No activity returned by this provider.</p>:activity.slice(0,10).map(a=><div className="stat" key={a.id}><span>{a.side??"Trade"} · {a.traderAddress?a.traderAddress.slice(0,8):"unknown"}…</span><span>{a.amountUsd!=null?"$"+a.amountUsd.toLocaleString():"—"}</span></div>)}</section></main>;
}