import type {Market,MarketActivity} from "@rush/types"; import type {MarketProvider} from "../provider.js"; import {GeckoTerminalClient} from "./client.js";
type Pool={id:string;attributes:{name:string;base_token_price_usd:string|null;price_change_percentage:{h24:string|null};market_cap_usd:number|null;volume_usd:{h24:string|null};reserve_in_usd:string|null;image_url?:string|null};relationships?:{base_token?:{data?:{id:string}}}}; type Pools={data:Pool[]};
type Trade={id:string;attributes:{block_timestamp:string;kind:string;volume_in_usd?:string|null;tx_hash?:string|null;tx_from_address?:string|null}};
const tokenAddress=(x:Pool)=>x.relationships?.base_token?.data?.id?.replace(/^base_/,"")??x.id;
const normalize=(x:Pool):Market=>{const a=x.attributes;const address=tokenAddress(x);return{id:"base:"+x.id,provider:"base",chain:"base",kind:"pool",name:a.name,symbol:a.name.split(" / ")[0]??a.name,address,marketAddress:x.id,priceUsd:a.base_token_price_usd?Number(a.base_token_price_usd):undefined,priceChange24h:a.price_change_percentage?.h24?Number(a.price_change_percentage.h24):undefined,marketCapUsd:a.market_cap_usd??undefined,volume24hUsd:a.volume_usd?.h24?Number(a.volume_usd.h24):undefined,liquidityUsd:a.reserve_in_usd?Number(a.reserve_in_usd):undefined,imageUrl:a.image_url??undefined,updatedAt:new Date().toISOString(),sourceUrl:"https://www.geckoterminal.com/base/pools/"+x.id};};
export class BaseProvider implements MarketProvider{
 readonly name="base"; constructor(private readonly client:GeckoTerminalClient){}
 private poolAddress(id:string){const raw=id.replace("base:","");return raw.startsWith("base_")?raw.slice(5):raw;}
 async listMarkets({limit}:{limit:number}){const data=await this.client.get<Pools>("/networks/base/pools?page=1&include=base_token");return{items:data.data.slice(0,limit).map(normalize)};}
 async getMarket(id:string){const data=await this.client.get<{data:Pool}>("/networks/base/pools/"+this.poolAddress(id)+"?include=base_token");return data.data?normalize(data.data):null;}
 async getAsset(address:string){const data=await this.client.get<{data:{attributes:{name:string;symbol:string;price_usd:string|null;market_cap_usd:number|null;image_url?:string|null}}}>("/networks/base/tokens/"+address);const a=data.data.attributes;return{id:"base-asset:"+address,provider:"base",chain:"base",kind:"asset",name:a.name,symbol:a.symbol,address,priceUsd:a.price_usd?Number(a.price_usd):undefined,marketCapUsd:a.market_cap_usd??undefined,imageUrl:a.image_url??undefined,updatedAt:new Date().toISOString(),sourceUrl:"https://www.geckoterminal.com/base/tokens/"+address};}
 async getQuoteAssets(){return [];}
 async getMarketActivity(id:string,limit:number){const data=await this.client.get<{data:Trade[]}>("/networks/base/pools/"+this.poolAddress(id)+"/trades");return data.data.slice(0,limit).map(row=>({id:"base:"+row.id,marketId:id,provider:"base",occurredAt:row.attributes.block_timestamp,side:row.attributes.kind,amountUsd:row.attributes.volume_in_usd?Number(row.attributes.volume_in_usd):undefined,traderAddress:row.attributes.tx_from_address??undefined,transactionHash:row.attributes.tx_hash??undefined} as MarketActivity));}
 async searchMarkets(queryText:string,limit:number){const data=await this.client.get<Pools>("/search/pools?query="+encodeURIComponent(queryText)+"&include=base_token");return data.data.filter(x=>x.id.startsWith("base_")).slice(0,limit).map(normalize);}
}